### ISSUE TITLE
Issue with MIssing Exposed folder

### ISSUE THREAD

**Issue by mark-a-j-adriano** [nswdpc/silverstripe-recaptcha-v3#2]
<img width="1165" alt="Screen Shot 2021-12-08 at 4 44 33 PM" src="https://user-images.githubusercontent.com/11882563/145148465-5719f8c3-6c47-41d8-b818-5fff9fd58b7d.png">

- SilverStripe CMS 4.8
- PHP 7.4
- Silverstripe Cloud
- Code Builder 1.0.2 (basic)

**Comment by JamesDPC** [comment]
Looks like the `SymlinkMethod` ignores non-existent target directories, whereas the CopyMethod understandably fails: https://github.com/silverstripe/vendor-plugin/blob/1/src/VendorExposeTask.php#L149

Thanks for the PR.
