### ISSUE TITLE
Silverstripe 5 compatibility

### ISSUE THREAD

**Issue by guyvanbael** [nswdpc/silverstripe-recaptcha-v3#9]
Are there plans to make this SS5 compatible?

**Comment by JamesDPC** [comment]
Absolutely, here's a start:

https://github.com/nswdpc/silverstripe-recaptcha-v3/compare/master...ss5

Happy to have any PRs on that branch, I can tag some 1.0 RC candidate versions as well.

**Comment by guyvanbael** [comment]
@JamesDPC just tested it on a ss5 project on my local machine (using docker and mailhog) and it's working perfectly

**Comment by JamesDPC** [comment]
Thanks for the update. I'll tag an rc release.

**Comment by michalkleiner** [comment]
Hi @JamesDPC, would there be any update on merging the ss5 branch and tagging either 0.4 or 1.0 version? CMS 5 is out for a while now and it would be great to have this module compatible. Thank you!

**Comment by JamesDPC** [comment]
> Hi @JamesDPC, would there be any update on merging the ss5 branch and tagging either 0.4 or 1.0 version? CMS 5 is out for a while now and it would be great to have this module compatible. Thank you!

Hi @michalkleiner - please see the latest v1.0.0 just tagged on both modules.

**Comment by michalkleiner** [comment]
Thanks @JamesDPC, I see 1.0.0 for the userforms module, but not here. Did you perhaps forget to push the tag here?

**Comment by JamesDPC** [comment]
I did! That's been fixed, thanks for the nudge.
